# version: '3.8'

services:
  db:
    image: postgres:12.7
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_default_db
    volumes:
      - ./create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
    networks:
      nw:
        ipv4_address: 192.168.0.47

networks:
  nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
